name: Lint and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Check style
      run: |
        tox -e style

    - name: Run tests
      run: |
        tox -e py312
